### ISSUE TITLE
播放器在播放m3u8格式时有错误哦~

### ISSUE THREAD

**Issue by 504750975** [gzlock/danplayer#2]
视频的时间会出现错误 他只会计算第一个切割的时间虽然随着加载进度条会变长但是只会显示0~59秒，比如1个小时的视频被切割了60份他就会显示60个0~59秒....

**Comment by gzlock** [comment]
可以提供一个m3u8的播放网址用来测试吗？

**Comment by 504750975** [comment]
必须OK https://wuji.zhulong-zuida.com/20191006/10309_f9b8be90/index.m3u8  





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yeoman"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 晚上9:38
收件人:&nbsp;"gzlock/danplayer"<danplayer@noreply.github.com&gt;;
抄送:&nbsp;"ヽ守一份执着ら"<504750975@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gzlock/danplayer] 播放器在播放m3u8格式时有错误哦~ (#2)




可以提供一个m3u8的播放网址用来测试吗？

**Comment by gzlock** [comment]
修复了

**Comment by gzlock** [comment]
从v0.0.35开始支持自定义时间格式了，使用说明在 [wiki]( https://github.com/gzlock/danplayer/wiki/DanPlayer类的完整参数字段讲解)
