### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by 504750975** [gzlock/danplayer#3]
就是如果视频的每一秒都只有一个弹幕的时候 弹幕只会在视频的最上面显示，感觉很单调的说，不知道作者能不能优化下，让他能随机在某个位置出现而不是一直只在第一排出现。同一秒的弹幕都是一排出现感觉怪怪的 不自然。

**Comment by 504750975** [comment]
不知道怎么发图。。。

**Comment by 504750975** [comment]
https://ae01.alicdn.com/kf/Hba7cfb1fa3ac4c449bbdcc3033c9449f0.jpg

https://ae01.alicdn.com/kf/H5477417d76994ab5ac0935b336d1bf665.jpg

图片链接

**Comment by gzlock** [comment]
原则是遵循B站这些大站的弹幕排位规则的体验

**Comment by 504750975** [comment]
我发了两张截图 有一张是B站的 那个有快有慢 看起来很舒服




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yeoman"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 下午2:52
收件人: "gzlock/danplayer"<danplayer@noreply.github.com&gt;; 
抄送: "ヽ守一份执着ら"<504750975@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gzlock/danplayer] 提个建议 (#3)




原则是遵循B站这些大站的弹幕排位规则的体验

**Comment by gzlock** [comment]
快慢也有实现的，跟b站一样：弹幕越长移动速度越快。

**Comment by 504750975** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yeoman"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 下午2:55
收件人: "gzlock/danplayer"<danplayer@noreply.github.com&gt;; 
抄送: "ヽ守一份执着ら"<504750975@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gzlock/danplayer] 提个建议 (#3)




快慢也有实现的，跟b站一样：弹幕越长移动速度越快。
 
&mdash;

**Comment by gzlock** [comment]
在功能上复刻(chao)b站是很彻底的
