### ISSUE TITLE
兼容问题 手机端自适应比较差

### ISSUE THREAD

**Issue by aaaol** [gzlock/danplayer#4]
![QQ截图20191209205208](https://user-images.githubusercontent.com/28624574/70437666-161c7800-1ac7-11ea-8333-d4941d8a37ce.png)

**Comment by aaaol** [comment]
![](https://tvax2.sinaimg.cn/large/6ea2dd75gy1g9qrildwqij20ai0bst8p.jpg)

**Comment by gzlock** [comment]
其实没有适配过手机😂

因为我知道国内的手机浏览器app和聊天app，都会用自行实现的视频组件代替的\<video\>标签
